services:
  simple-app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      # model files
      - ./models:/root/.cache/huggingface
    ports:
      - '8081:8080'
